# -*- coding: utf-8 -*-
"""The Hungry City Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gy9SOT_7UgRrjMIKCwzQ8DUOYvJibbHh

#Environment Setup
"""

pip install overpass

import requests
import pandas as pd

# Overpass API URL
url = "http://overpass-api.de/api/interpreter"

# The 'Query' - Asking for restaurants in Yangon
query = """
[out:json];
area["name"="Yangon"]->.searchArea;
(
  node["amenity"="restaurant"](area.searchArea);
  way["amenity"="restaurant"](area.searchArea);
  node["amenity"="cafe"](area.searchArea);
  way["amenity"="cafe"](area.searchArea);
);
out center;
"""

response = requests.get(url, params={'data': query})
data = response.json()

# Parse the Open Data
restaurants = []
for element in data['elements']:
    name = element.get('tags', {}).get('name', 'Unnamed')
    cuisine = element.get('tags', {}).get('cuisine', 'Unknown')
    lat = element.get('lat') or element.get('center', {}).get('lat')
    lon = element.get('lon') or element.get('center', {}).get('lon')

    restaurants.append({"Name": name, "Cuisine": cuisine, "Lat": lat, "Lon": lon})

df = pd.DataFrame(restaurants)
print(f"✅ Success! Found {len(df)} restaurants for FREE.")
print(df.head())

import requests
import pandas as pd

# Overpass API URL
url = "http://overpass-api.de/api/interpreter"

# Define a bounding box for Yangon [south, west, north, east]
# This covers the core city area
bbox = "16.76,96.10,16.88,96.22"

query = f"""
[out:json];
(
  node["amenity"="restaurant"]({bbox});
  way["amenity"="restaurant"]({bbox});
  node["amenity"="cafe"]({bbox});
  way["amenity"="cafe"]({bbox});
  node["amenity"="fast_food"]({bbox});
);
out center;
"""

print(" Querying OpenStreetMap for Yangon core...")
response = requests.get(url, params={'data': query})
data = response.json()

restaurants = []
for element in data.get('elements', []):
    tags = element.get('tags', {})
    lat = element.get('lat') or element.get('center', {}).get('lat')
    lon = element.get('lon') or element.get('center', {}).get('lon')

    restaurants.append({
        "Name": tags.get('name', 'Unnamed'),
        "Cuisine": tags.get('cuisine', 'Unknown'),
        "Type": tags.get('amenity'),
        "Lat": lat,
        "Lon": lon
    })

df = pd.DataFrame(restaurants)

if not df.empty:
    print(f"✅ Success! Found {len(df)} locations.")
    print(df.head())
else:
    print("❌ Still 0. Let's try an even wider area.")

print(df['Cuisine'].value_counts())

import folium
from folium.plugins import HeatMap

# 1. Initialize the map centered on Yangon
m = folium.Map(location=[16.82, 96.16], zoom_start=13, tiles="cartodbpositron")

# 2. Filter out any rows that might have missing coordinates (just in case)
heat_data = df[['Lat', 'Lon']].dropna().values.tolist()

# 3. Add the Heatmap layer
HeatMap(heat_data, radius=15, blur=10).add_to(m)

# 4. Save and display
m.save("yangon_food_heatmap.html")
m

# Simple rounding to 'cluster' restaurants by area
df['lat_cluster'] = df['Lat'].round(3)
df['lon_cluster'] = df['Lon'].round(3)

top_neighborhoods = df.groupby(['lat_cluster', 'lon_cluster']).size().reset_index(name='count')
print("🔥 Top 5 Food Hotspots (Coordinates):")
print(top_neighborhoods.sort_values(by='count', ascending=False).head(5))

"""#Data Cleaning

1. Fix the unkown cuisines(Imputation)
Don't want to delet the 'unknows'-there are 90% of fata. Instead, use the Type (amenity_ to fill in the gaps.
If its a cafe, its likely servering Coffee/Tea/
If its fast_food, categorize it as 'Quick Service'.
"""

#Create a 'Cleaned_cuisine' column
def categorize_cuisine(row):
  cuisine=str(row['Cuisine']).lower()
  amenity=str(row['Type']).lower()

  if 'unkown' in cuisine or cuisine =='nan':
    if 'cafe' in amenity:
      return 'Cafe & Bakery'
    elif 'fast_food' in amenity:
      return 'Quick Service'
    else:
      return 'General Dinning'
  return cuisine.capitalize()

"""2. Standardize Names & Remove Duplicates
Sometimes the same restaurant is listed twice (e.g.,"KFC" and "KFC-Junction-City").
Strip whitespace: remove extra spaces.
Lowercase matching: Ensure "Shan Yoe Yar" and "shan yoe yar" are counted as the same.
Remove Duplicates: Drop rows with the exact same name and location.
"""

#Clean names
df['Name']=df['Name'].str.strip().str.title()

#Remove Duplicates based on Name and Coordinates (Rounded to 4 decimal places)
df['Lat_round'] = df['Lat'].round(4)
df['Lon_round'] = df['Lon'].round(4)
df = df.drop_duplicates(subset=['Name', 'Lat_round', 'Lon_round'])

print(f"Total unique Restaurants:{len(df)}")

import matplotlib.pyplot as plt
import pandas as pd

# 1. Define the cleaning logic
def categorize_cuisine(row):
    # Get the raw values, handle 'None' or 'NaN'
    cuisine = str(row.get('Cuisine', 'unknown')).lower()
    amenity = str(row.get('Type', 'restaurant')).lower()

    # If the cuisine is missing/unknown, use the 'Type' to guess
    if cuisine in ['unknown', 'nan', 'none', '']:
        if 'cafe' in amenity:
            return 'Cafe & Bakery'
        elif 'fast_food' in amenity:
            return 'Quick Service'
        elif 'bar' in amenity or 'pub' in amenity:
            return 'Bar & Nightlife'
        else:
            return 'General Dining'

    # If it's a list like "regional;chinese", just take the first part
    return cuisine.split(';')[0].strip().capitalize()

# 2. APPLY the function to create the column (The missing step!)
df['Cleaned_Cuisine'] = df.apply(categorize_cuisine, axis=1)

# 3. Clean up the names and remove duplicates for a better chart
df['Name'] = df['Name'].str.strip().str.title()
df = df.drop_duplicates(subset=['Name', 'Lat', 'Lon'])

# 4. Prepare data for the chart
top_cuisines = df['Cleaned_Cuisine'].value_counts().head(10)

# 5. Plot the results
if not top_cuisines.empty:
    plt.figure(figsize=(10, 6))
    colors = ['#FF5733', '#33FF57', '#3357FF', '#F333FF', '#FF3380',
              '#33FFF5', '#F5FF33', '#FFA533', '#8D33FF', '#33FF8D']

    top_cuisines.plot(kind='barh', color=colors[:len(top_cuisines)])

    plt.title('Yangon Food Scene: Top 10 Categories', fontsize=14, fontweight='bold')
    plt.xlabel('Number of Establishments')
    plt.ylabel('Category')
    plt.gca().invert_yaxis()
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

    print("\n✅ Data successfully cleaned and plotted!")
    print(f"Total unique restaurants analyzed: {len(df)}")

